// This file is part of ariadne.
//
// ariadne is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// ariadne is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
// PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// ariadne. If not, see <https://www.gnu.org/licenses/>.

#ifndef XrfBase_h_
#define XrfBase_h_

#include "ScriptAccess.h"
#include "CaseAwareString.h"
#include "SourceLoc.h"

/// Represents something you can cross reference
/// This is a port, signal, constant or generic
class XrfBase : public ScriptAccess
{
public:
  XrfBase(const CaseAwareString & name, const CaseAwareString & type,
          int portOrder=-1, SourceLoc loc=0);
  virtual ~XrfBase();

  const CaseAwareString & getName() const;
  const CaseAwareString & getNameOrigCase() const;
  CaseAwareString getBasename() const;
  const CaseAwareString & getType() const;
  void setType(const CaseAwareString & type);
  virtual bool isSignalPort() const = 0;
  // To keep the order of the ports as it was when they where read in
  void overridePortOrder(unsigned int order);
  unsigned int getPortOrder() const;
  SourceLoc loc() const { return loc_; }

  static bool generating;

private:
  CaseAwareString name_;
  CaseAwareString type_;
  CaseAwareString nameOrigCase_;
  CaseAwareString initialValue_;
  bool autoGenerated_;
  unsigned int portOrder_;
  SourceLoc loc_;
};

#endif
